POST http://localhost:8080/api/chat-process HTTP/1.1
content-type: application/json

{
    "prompt": "列出旅游景点列表"
}

###

POST http://localhost:8080/api/chat-process HTTP/1.1
content-type: application/json

{
    "prompt": "中国的",
    "options":{
        "conversationId":"d060898e-09fb-46c2-b14c-3e7662976000"
    }
}

###


POST http://localhost:8080/api/chat-process HTTP/1.1
content-type: application/json

{
    "prompt": "第一个",
    "options":{
        "conversationId":"d060898e-09fb-46c2-b14c-3e7662976000"
    }
}

###